### ISSUE TITLE
Allow for use of plugin within refactor/rename window

### ISSUE THREAD

**Issue by dsrikrishna** [netnexus/camelcaseplugin#1]
Currently the plugin works great when used within the editor, but when renaming function a dialog box opens up (within Pycharm). It would be great if this plugin could support this use case as well.

![image](https://user-images.githubusercontent.com/21349274/55004742-26300e00-4fb1-11e9-8d3f-d6c534b95679.png)

**Comment by johannespfeiffer** [comment]
Makes sense.

Already done by @wagner-netnexus in 13c23a0e1c403ee3abaad05d5969e46c4dd84192 some time ago.

Will create a new release.

**Comment by dsrikrishna** [comment]
Great! Appreciate the great work! Looking forward to the release.
