### ISSUE TITLE
The unconfigureable camelCase shortcut conflicts with PhpStorms Open UML Dialog

### ISSUE THREAD

**Issue by pvdhurk** [netnexus/camelcaseplugin#11]
The shortcut `option+cmd+U` hardcoded in your plugin in PhpStorm 2020.2 is assigned to open the UML Dialog.
The workaround is changing the UML Dialog shortcut, but ideally this plugin opens the shortcut to be configurable instead

**Comment by raveren** [comment]
not unconfigurable 

![image](https://user-images.githubusercontent.com/364220/131342867-fc80630c-6894-4dfa-b30a-3c4e2347338b.png)

**Comment by wagner-netnexus** [comment]
It is configurable in _Preferences -> Keymap -> Plugins -> CamelCase -> Toggle Camel Case_:
<img width="978" alt="1" src="https://user-images.githubusercontent.com/47000926/145833727-8d053b66-5200-4b40-afae-c480bd607a96.png">
