### ISSUE TITLE
Need a license

### ISSUE THREAD

**Issue by wcarmon** [netnexus/camelcaseplugin#12]
@johannespfeiffer  Can you select a license for this plugin (eg. GPL 3).  

Our company won't allow us to use this fantastic plugin without a license.

These might help with your decision
- https://choosealicense.com
- https://ufal.github.io/public-license-selector/

**Comment by wagner-netnexus** [comment]
license added in https://github.com/netnexus/camelcaseplugin/commit/eb2ebe84544696147a293ca1533dbe66527d723a
