### ISSUE TITLE
Problems with idea VIM

### ISSUE THREAD

**Issue by jacekgajek** [netnexus/camelcaseplugin#14]
Thanks for a great plugin!

I tried to assign `ToggleCamelSnakeCase` action as a macro like this:

```
:map gu :action ToggleCamelSnakeCase<CR>
```
but it does nothing

I have other actions defined which work as expected, eg
```
:map gi :action GotoImplementation<CR>
:map gt :action GotoTypeDeclaration<CR>
:map zr :action RefactoringMenu<CR>
:map zs :action SurroundWith<CR>
```

Any Ideas?

Greetings - Jacek

**Comment by C0d3Br3aker** [comment]
You can assign this action with this line:
`map gu <Action>(de.netnexus.CamelCasePlugin.ToggleCamelCase)`

**Comment by wagner-netnexus** [comment]
You can assign this action with this line:
`map gu <Action>(de.netnexus.CamelCasePlugin.ToggleCamelCase)`
