### ISSUE TITLE
Not working with multi-cursor anymore

### ISSUE THREAD

**Issue by putopavel** [netnexus/camelcaseplugin#2]
I am 100% sure that a couple of days ago I was able to use this plugin with multiple cursors on the editor. Now I'm not able anymore and it's really annoying :disappointed:.

Some info:
> CamelCase version: 3.0.0
> IntelliJ IDEA 2019.1.2 (Ultimate Edition)
> Build #IU-191.7141.44, built on May 7, 2019
> JRE: 1.8.0_202-release-1483-b49 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.15.0-45-generic

**Comment by johannespfeiffer** [comment]
Hi, thank you, good catch!
Just fixed it and released a new version 3.0.1.
