### ISSUE TITLE
Where is Android studio preference file

### ISSUE THREAD

**Issue by Ni3verma** [netnexus/camelcaseplugin#24]
In your documentation you have mentioned below:

> Please have a look at the preferences of this plugin: You can disable some conversions or change their order.

Where can I find preference of a plugin in android studio in Apple M1 ?

**Comment by josealesuarezh** [comment]
![image](https://github.com/netnexus/camelcaseplugin/assets/76010532/9b92763f-9550-49e3-9358-bc390e016b23)

This is from PHP storm, but it may help you.

**Comment by Ni3verma** [comment]
Thanks a lot, found it !
<img width="364" alt="image" src="https://github.com/netnexus/camelcaseplugin/assets/20037625/af9e30cb-37c8-4098-9c6b-7bd03644247a">
