### ISSUE TITLE
Not working with PHP $variablesInCamelCase

### ISSUE THREAD

**Issue by pliszka2** [netnexus/camelcaseplugin#5]
**Steps to reproduce**
- create function 
`function function_name($firstParamName) {}`
- set cursor on $firstParamName
- hit ALT+ SHIFT + U 

**Actual result**
- nothing happend 

**Expected result**
- iterate through kebab-case, SNAKE_CASE, PascalCase, camelCase, snake_case or space case

**Additional info**
- when param name is $first_param_name when we hit ALT+ SHIFT + U we get $firstParamName (so that's correct) 
- when you select variable name without $ character it's looks work fine 
- using on string $s1 = 'simpleString'; works fine 
- PHPStorm version 2019.3.3

**Comment by johannespfeiffer** [comment]
@wagner-netnexus could you please have a look?

**Comment by johannespfeiffer** [comment]
@pliszka2 Thank you for the report.
Should be fixed in 3.0.3

**Comment by pliszka2** [comment]
@johannespfeiffer Works Perfect Thanks!
