### ISSUE TITLE
Not working with string 'some-string-with-dashes'

### ISSUE THREAD

**Issue by pliszka2** [netnexus/camelcaseplugin#6]
**Steps to reproduce**

- create string definition
```PHP
$string = 'some-string-with-dashes';
```
- set cursor on somewhere on 'some-string-with-dashes' 
- hit ALT+ SHIFT + U

**Actual result**

- only single word is selecting

**Expected result**

iterate through kebab-case, SNAKE_CASE, PascalCase, camelCase, snake_case or space case

**Additional info**

If you select whole text by hand it's works perfect

Would be great it that could also work in template literals:

```JS
const templateLiteral = `This is ${some-varialbe} and te rest of the text`;
const templateLiteral = `This is ${some_varialbe} and te rest of the text`;
const templateLiteral = `This is ${someVarialbe} and te rest of the text`;
const templateLiteral = `This is ${some varialbe} and te rest of the text`;
const templateLiteral = `This is ${SomeVarialbe} and te rest of the text`;
```

**Comment by wagner-netnexus** [comment]
Fixed in 3.0.8
