### ISSUE TITLE
Title case support

### ISSUE THREAD

**Issue by ikerasLT** [netnexus/camelcaseplugin#8]
**Steps to reproduce**

- create string `'Article No'`
- select entire string
- hit ALT+ SHIFT + U

**Actual result**

`'article No'` -> `'article _no'` -> `'article--no'` -> `'article  no'` (double space) -> `'ARTICLE__NO'` -> `'Article_No'`-> `'article__no'`

**Expected result**

iterate through:
 `'articleNo'` -> `'article_no'` -> `'article-no'` -> `'article no'` (single space) -> `'ARTICLE_NO'` -> `'ArticleNo'`-> `'article_no'`

Additional info

- when words in string is lowercase `'article no'` when we hit ALT+ SHIFT + U we get `'ARTICLE_NO'` (so that's correct)
- PHPStorm version 2020.1

**Comment by wagner-netnexus** [comment]
Supported in 3.0.8
